doctors/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.doctors, name='doctors'),
    path('doctor_profile/', views.doctor_profile, name='doctor_profile'),
    path('', views.doctor_register, name='doctor_register'),
    path('search/', views.search_view, name='search_doctors'),
    path('details/<int:doctor_id>/', views.doctor_details, name='doctor_details'),
]

doctors/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from accounts.models import Account

class DoctorModel(models.Model):
    doctor_id = models.AutoField(primary_key=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='doctor', null=True, blank=True)
    # account = models.OneToOneField(Account, on_delete=models.CASCADE, related_name='doctor', default=None)
    designation = models.CharField(max_length=255)
    speciality = models.CharField(max_length=255)
    experience = models.CharField(max_length=255)
    date_joined = models.DateTimeField(auto_now_add=True)

    # Appointment availability for multiple days
    APPOINTMENT_DAYS_CHOICES = [
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday'),
    ]
    appointment_available_days = models.CharField(max_length=100, choices=APPOINTMENT_DAYS_CHOICES, blank=True, null=True)

    def __str__(self):
        return str(self.account.first_name + " " + self.account.last_name + ' - ' + self.designation + ' - ' + self.speciality) 

doctors/forms.py
from django import forms
from . import models

class DoctorForm(forms.ModelForm):
    class Meta:
        model = models.DoctorModel
        fields = ('experience', 'designation', 'speciality', 'appointment_available_days')

    def __init__(self, *args, **kwargs):
        super(DoctorForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

doctors/views.py
from django.shortcuts import render
from .forms import DoctorForm
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users, admin_only, unauthenticated_user
from django.shortcuts import render, redirect, get_object_or_404
from .models import DoctorModel
from django.contrib import messages, auth
from .forms import DoctorForm
from patients.forms import SearchForm
from django.db.models import Q

# Create your views here.
def doctors(request):
    doctors = DoctorModel.objects.all().order_by('-date_joined')
    is_doctor = False
    search_form = SearchForm()
    if request.user.is_authenticated:
        is_doctor = DoctorModel.objects.filter(account=request.user).exists()

    return render(request, 'doctors/doctors_list.html', {'doctors' : doctors, 'is_doctor': is_doctor, 'search_form': search_form})




@login_required(login_url='login')
def doctor_profile(request):
    doctor = DoctorModel.objects.get(account=request.user)
    doctor_form = DoctorForm(instance=doctor)

    if request.method == 'POST':
        doctor_form = DoctorForm(request.POST, instance=doctor)
        if doctor_form.is_valid():
            doctor_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('dashboard')
        else: 
            redirect('dashboard')

    return render(request, 'doctors/doctor_profile.html', {'doctor_form': doctor_form, 'doctor': doctor})
    

@login_required(login_url='login')
def doctor_register(request):
    form = DoctorForm()
    if request.method == 'POST':
        form = DoctorForm(request.POST)
        if form.is_valid():
            doctor = form.save(commit=False)
            doctor.account = request.user
            doctor.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('dashboard')
        else: 
            redirect('dashboard')
    else:
        form = DoctorForm()
    return render(request, 'doctors/doctor_register.html', {'form': form})


def search_view(request):
    search_form = SearchForm()

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            doctors = DoctorModel.objects.order_by('-date_joined').filter(Q(account__first_name__icontains=keyword) | Q(designation__icontains=keyword) | Q(account__last_name__icontains=keyword) | Q(speciality__icontains=keyword) | Q(account__email__icontains=keyword))
            doctors_count = doctors.count()
    context = {
        'doctors': doctors,
        'd_count': doctors_count,
        'search_form': search_form,
    }
    return render(request, 'doctors/search_results.html', context) 


def doctor_details(request, doctor_id):
    doctor = get_object_or_404(DoctorModel, pk=doctor_id)
    return render(request, 'doctors/doctor_details.html', {'doctor': doctor})

doctors/templates/doctors/doctor_details.html
{% extends "base.html" %} {% block content %}
<div class="container" style="margin-top:150px;margin-left:80px; align-items:center">
  <div class="row">
    <h1>Doctor Details</h1>
    <img src="{{doctor.account.profile.profile_picture.url}}" alt="{{doctor.doctor_id}}" style="width:200px; border-radius:50%; text-align:center"> <br>
    <br>
    <p><strong>Doctor ID:</strong> {{ doctor.doctor_id }}</p>
    <p>
      <strong>Doctor Name:</strong> {{ doctor.account.first_name }} {{doctor.account.last_name }}
    </p>
    <p><strong>Designation:</strong> {{ doctor.designation }}</p>
    <p><strong>Speciality:</strong> {{ doctor.speciality }}</p>
    <p><strong>Experience:</strong> {{ doctor.experience }}</p>
    <p>
      <strong>Appointment Availability:</strong> {{doctor.get_appointment_available_days_display }}
    </p>
    <!-- Add more doctor details here as needed -->

    <!-- Example: Display a list of patients associated with this doctor -->
    <h2>Patients Associated with {{ doctor.account.first_name }}:</h2>
    <ul>
      {% for patient in doctor.appointment.all %} 
      <li>{{ patient.patient_name }} - Age: {{ patient.patient_age }} - Diesease/Syndrome : {{patient.disease_syndrome}}</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

doctors/templates/doctors/doctor_profile.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'accounts/dashboard_sidebar.html' %}
	<main class="col-md-9 bg-info" style="margin-top:150px">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit your doctor's profile</strong>

		</header>
		{% if userprofile.profile_picture %}
		<img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="150" height="150" style="border-radius:50%; width:150px; align:center; margin: 20px 600px 0 60px">
		{% endif %} 
		<div class="card-body">
			<div class="text-right">
				
			</div>
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'doctor_profile' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-row d-flex">
						<div class="form-group col-md-6">
							<label>Designation</label>
							{{doctor_form.designation}}
						</div>
						<div class="form-group col-md-6">
							<label>Speciality</label>
							{{doctor_form.speciality}}
						</div>
					</div>
					
					<div class="form-row d-flex">
						<div class="form-group col-md-6">
							<label>Appoinments Availability</label>
							{{doctor_form.appointment_available_days}}
						</div>
						<div class="form-group col-md-6">
							<label>Other's Information</label>
							{{doctor_form.experience}}
						</div>
						
					</div>
					<br>
					<input type="submit" value="Save" class="btn btn-primary">
				</form>
			</div> 

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

doctors/templates/doctors/doctor_register.html
{% extends 'base.html' %}


{% block content %}

<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:140px;">
      <article class="card-body">
    {% include 'includes/alerts.html' %}
		<header class="mb-4"><h4 class="card-title">Doctor Registration</h4></header>
		<form action="{% url 'doctor_register' %}" method="POST">
      {% csrf_token %}


				<div class="form-row">
					<div class="col form-group">
						<label>Designation</label>
					  	{{ form.designation }}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Experience</label>
					  	{{ form.experience }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->


				<div class="form-row d-flex">
					<div class="form-group col-md-6">
					  <label>Speciality</label>
					  {{form.speciality}}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
					  <label>Available</label>
					  {{form.appointment_available_days}}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->
      {{ form.email.errors }}
      {{ form.non_field_errors }}
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>

{% endblock %}

doctors/templates/doctors/doctors_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    
    {% if not is_doctor %}
    <div class="mx-auto" style="margin-top:150px;width:50%; text-align:center;">
        <div class="card">
            If you're a doctor, please <a href="{% url 'login' %}">login</a> to your account. Then create a <a href="{% url 'doctor_register' %}">doctor profile</a> as a doctor.
        </div>

    </div>
    {% endif %}

    <div class="doctor-list" style="margin-top:150px; text-align:center;">
        <h4  style="text-align:center;">Doctor's List:</h4> <br>

        <div class="w-100 text-center">
          <form action="search" method="get">
              {% csrf_token %}
              {{search_form}}
              <button type="submit" class="btn btn-primary">Search</button>
          </form>
            
      </div>
<table class="table table-hover p-5" style="padding:20px;text-align:center;">
  <thead>
    <tr>
      <th scope="col">Doctor ID</th>
      <th scope="col">Full Name</th>
      <th scope="col">Email</th>
      <th scope="col">Designation</th>
      <th scope="col">Speciality</th>
      <th scope="col">Experience</th>
      <th scope="col">Availability</th>
      <th scope="col">See Details</th>
    </tr>
  </thead>
  <tbody>
    {% for doctor in doctors %}
    
    <tr>
      <th scope="row">{{doctor.doctor_id}}</th>
      <td>{{doctor.account.first_name}} {{doctor.account.last_name}}</td>
      <td>{{doctor.account.email}}</td>
      <td>{{doctor.designation}}</td>
      <td>{{doctor.speciality}}</td>
      <td>{{doctor.experience}}</td>
      <td>{{doctor.appointment_available_days}}</td>
      <td><a href="{% url 'doctor_details' doctor.doctor_id %}" class="btn btn-danger">View</a></td>
    </tr>
    
    {% endfor %}
  </tbody>
</table>
    </div>
{% endblock %}

doctors/templates/doctors/search_results.html
{% extends "base.html" %}

{% block content %}
<div style="margin-top:150px; text-align:center; justify-content:center; align-items:center"></div>
<h1>Search Results</h1>
    <form method="get">
        {{ search_form }}
        <button type="submit">Find</button>
    </form>
    <ul>
        {% if doctors %}
        <li>{{d_count}} results found.</li>
        <table class="table table-hover p-5" style="padding:20px;text-align:center;">
            <thead>
                <tr>
                    <th scope="col">#ID</th>
                    <th scope="col">Doctor Name</th>
                    <th scope="col">Designation</th>
                    <th scope="col">Speciality</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Experiences </th>
                    <th scope="col">Availability</th>
                    <th scope="col">Join Date</th>
                </tr>
            </thead>
            <tbody>
                
            {% for item in doctors %}
                  
                  <tr>
                    <th scope="row">{{item.doctor_id}}</th>
                    <th scope="row">{{item.account.first_name}} {{item.account.last_name}}</th>
                    <td scope="row">{{item.designation}}</td>
                    <td scope="row">{{item.speciality}}</td>
                    <td scope="row">{{item.account.email}}</td>
                    <td scope="row">{{item.experience}}</td>
                    <td scope="row">{{item.appointment_available_days}}</td>              
                    <td scope="row">{{item.date_joined}}</td>              
                  </tr>
                  {% endfor %}
                  
                  
                </tbody>
              </table>
        {% else %}
            <li>No results found.</li>
        {% endif %}
</ul>
{% endblock %}